import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    'prerequisites',
    'samples',
    'resources',
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: '01-gui-to-bui-to-dwc'},
        {type: 'autogenerated', dirName: '02-browser-developer-tools'},
        {type: 'autogenerated', dirName: '03-dwc-debugging'},
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '04-upgrading-apps'},
        {type: 'autogenerated', dirName: '05-dwc-controls'},
        {type: 'autogenerated', dirName: '06-flow-layouts'},
      ],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '07-icon-pools'},
        {type: 'autogenerated', dirName: '08-control-validation'},
        {type: 'autogenerated', dirName: '09-browser-constraints'},
        {type: 'autogenerated', dirName: '10-embedding-components'},
        {type: 'autogenerated', dirName: '11-advanced-responsive'},
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '12-deployment'},
      ],
    },
  ],
};

export default sidebars;
